### ISSUE TITLE
Lyrics API not responding?

### ISSUE THREAD

**Issue by duckyondiscord** [raitonoberu/sptlrx#30]
For about a week now, no lyrics have showed up in sptlrx, just blank, then I took a look at the output of `curl -G "https://lyricsapi.vercel.app/api/lyrics?lrc=1" --data-urlencode "name=$(playerctl metadata --format '{{artist}} {{title}}')"` as suggested by your comment in another issue, and it just returns nothing.

**Comment by duckyondiscord** [comment]
![image](https://github.com/raitonoberu/sptlrx/assets/94759537/48a51967-e11a-40e5-a37e-6bb983937a3a)

**Comment by raitonoberu** [comment]
Hello, @duckyondiscord!
Sorry for the inconvenience, the problem is that Spotify cookies on a public server tend to expire at a random time (or even reset my password due to *suspicious activity* xD). Sometimes after 3 months, sometimes after 30 days. But I swear I updated it like 3 days ago and it broke again. It's easy to fix but it takes time just to find out that it doesn't work.

Thank you for reporting, it should be working now. Let's leave this open and pin it so that anyone can report here next time.

**Comment by duckyondiscord** [comment]
> Hello, @duckyondiscord! Sorry for the inconvenience, the problem is that Spotify cookies on a public server tend to expire at a random time (or even reset my password due to _suspicious activity_ xD). Sometimes after 3 months, sometimes after 30 days. But I swear I updated it like 3 days ago and it broke again. It's easy to fix but it takes time just to find out that it doesn't work.
> 
> Thank you for reporting, it should be working now. Let's leave this open and pin it so that anyone can report here next time.

I'm using MPRIS and it's still not working for me :/

**Comment by devlocalhost** [comment]
i have the same issue. i even compiled the api only, and used my own cookie, but it still doesnt work:
![image](https://github.com/raitonoberu/sptlrx/assets/56504654/9f4572d8-318c-49c3-8d60-726eca97ffdb)
![image](https://github.com/raitonoberu/sptlrx/assets/56504654/e8c34a47-6146-447e-b67d-7dd816710193)

**Comment by raitonoberu** [comment]
This is strange because the API is currently working fine. Is there any lyrics for this track on Spotify? (sorry, I'm not near the pc rn)

**Comment by devlocalhost** [comment]
> This is strange because the API is currently working fine. Is there any lyrics for this track on Spotify? (sorry, I can't check it myself)

i tried with another track and it works. maybe make it a bit more obvious?? like, a message, and maybe add docs? (that the track does not have lyrics)

**Comment by devlocalhost** [comment]
> i have the same issue. i even compiled the api only, and used my own cookie, but it still doesnt work: ![image](https://user-images.githubusercontent.com/56504654/283994140-9f4572d8-318c-49c3-8d60-726eca97ffdb.png) ![image](https://user-images.githubusercontent.com/56504654/283994148-e8c34a47-6146-447e-b67d-7dd816710193.png)

this track does have lyrics on genius.com btw.

**Comment by duckyondiscord** [comment]
The same issue is happening again for me @raitonoberu 
Sorry to bother you.

**Comment by raitonoberu** [comment]
@duckyondiscord no worries, I'd like to know if there are problems that I can fix. right now the api seems to be working fine, what is your problem?

**Comment by duckyondiscord** [comment]
Tested it again today, now it works, must've been a one-time issue, sorry for the noise.

**Comment by raitonoberu** [comment]
At the moment, `lyricsapi.vercel.app` is just a fancy proxy to `lrclib.net`, and that's why we completely move away from the idea of a self-hosted server. Direct support for lrclib will added in future versions. Let's close the issue.
